services:
  back:
    build: ./back/api
    container_name: node_app
    volumes:
      - ./back/api/src:/app/src
      - /app/node_modules
    ports:
      - "3000:5000"
    environment:
      NODE_ENV: development
    depends_on:
      - db
  front:
    build: ./front/react-app
    container_name: react_app
    volumes:
      - ./front/react-app:/app
      - /app/node_modules
    ports:
      - "3001:5173"
    depends_on:
      - db
  db:
    image: mysql:8.1
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./back/config/sql/bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: