services:
  app:
    build: ./api
    container_name: node_app
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:5000"
    environment:
      NODE_ENV: development
    depends_on:
      - db
  db:
    image: mysql:8.1
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: