services:
  app:
    build: ./api
    container_name: node_app
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:5000"
    environment:
      NODE_ENV: development
    depends_on:
      - db
  db:
    image: mysql:8.1
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./config/sql/bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db